### ISSUE TITLE
Improve "Collection" Template

### ISSUE THREAD

**Issue by cthoyt** [jcheminform/jcheminform#12]
After a short discussion [on twitter](
https://twitter.com/egonwillighagen/status/1427159279291731968) about submitting a proposal for a collection on papers featuring reusable code, @egonw suggested I fill out an issue based on the [collection template](https://github.com/jcheminform/jcheminform/blob/master/.github/ISSUE_TEMPLATE/collection-proposal.md).

Unfortunately, I didn't really feel like I understood what was expected of me as an issue maker. First, it would be nice to have a link to a page on the J Chem Inf website that describes what a collection is and why someone would propose one, further than the more general submission guidelines link. Second, it would be nice to link to a really well-written previous issue as an example to the issue submitter. Right now, there are only [two total](https://github.com/jcheminform/jcheminform/issues?q=is%3Aissue+label%3A%22collection+proposal%22) and only one of them (https://github.com/jcheminform/jcheminform/issues/10) seems to be fully filled out - but even then, it still does not give me a sense of what would be expected/useful for me to write

**Comment by egonw** [comment]
There is no full example yet; so far, the main ticket text evolved over time (which I clarified in https://github.com/jcheminform/jcheminform/commit/d580b3be7af31e207992b3eecd0efcfcaeca1bef#diff-01465a857211e3463cd8fb37598cff17b004907e5e814ba9e2297fd077f911dd). I added some links and info about collections in https://github.com/jcheminform/jcheminform/commit/726d82cd422064bacbd185d6aa7444f95e9c158b#diff-01465a857211e3463cd8fb37598cff17b004907e5e814ba9e2297fd077f911dd

**Comment by cthoyt** [comment]
Thanks, @egonw. I think this will make it much easier for me to fill in the template
