### ISSUE TITLE
Indexing issue with Google Scholar for the MAYGEN paper

### ISSUE THREAD

**Issue by egonw** [jcheminform/jcheminform#17]
# MAYGEN: an open-source chemical structure generator for constitutional isomers based on the orderly generation principle: 10.1186/S13321-021-00529-9

## Checklist

 - [x] list in which indexer the problem is found
 - [x] describe how the indexing is wrong by comparing what you found and what you expect

## Description of the indexing issue

When I search this recent article in Google Scholar with the DOI of the article, only preprints show up and not the article itself:

![image](https://user-images.githubusercontent.com/26721/144039313-b262af53-7dea-45f0-ac3e-ab2a5b0e85ee.png)

**Comment by mjsmyllie** [comment]
- [x] Reported to indexing team
- [ ] Reported to Google Scholar
- [ ] Author notified of outcome

**Comment by egonw** [comment]
Seems to be fixed:

![image](https://user-images.githubusercontent.com/26721/169365723-75dd5c29-5229-4f22-ba86-3efc1ae45b15.png)
