### ISSUE TITLE
jcheminf.com website future

### ISSUE THREAD

**Issue by egonw** [jcheminform/jcheminform#18]
@mjsmyllie, once we had the jcheminf.com website. What is the future of that? Currently, it's offline for me:

![image](https://user-images.githubusercontent.com/26721/144553399-b8f572cc-12df-4d2c-b014-d6ddda5e944d.png)

and a reader mentions a SSL certificate problem: https://twitter.com/andrewwhite01/status/1466571873936936962

**Comment by mjsmyllie** [comment]
The domain jcheminf.com is no longer in use and has not been since 2016. The correct web address is https://jcheminf.biomedcentral.com/

**Comment by egonw** [comment]
I used to redirect for some time. We should figure out if we still link to it, or where it is linked to in the first place. Like old editorials?

**Comment by mjsmyllie** [comment]
It used to link to the old website, but when the platform was changed in 2016, all fully OA journals were transferred to springeropen.com or biomedcentral.com and the old URLs were set up to redirect. All content was transferred across to the new website. Authors/researchers should update their bookmarks.

**Comment by egonw** [comment]
- www.jcheminf.com redirects
- jcheminf.com does not redirect

**Comment by egonw** [comment]
Relevant because URL used in publisher PDFs, see https://twitter.com/andrewwhite01/status/1467120242220539913

![image](https://user-images.githubusercontent.com/26721/144711087-b99e93a9-beee-410d-964b-b997157997dd.png)

**Comment by mjsmyllie** [comment]
That paper was published in 2012, at which point that was the journal URL. 

Here is the layout of the article PDF from the most recently published article:
![image](https://user-images.githubusercontent.com/50145018/144817884-b80b8ae5-5e4e-49a8-8ef3-1b38e4d94383.png)
