### ISSUE TITLE
editorial missing from the CiTO collection

### ISSUE THREAD

**Issue by egonw** [jcheminform/jcheminform#20]
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-022-00597-5 has CiTO annotation but is not listed in the CiTO collection, where the most recent paper is a different paper:

![image](https://user-images.githubusercontent.com/26721/169365539-c6c8c95d-9a8a-44c3-8864-fc0a6c3b4129.png)

**Comment by mjsmyllie** [comment]
done

**Comment by egonw** [comment]
Cannot confirm it yet, but will assume it will be online tomorrow.

**Comment by egonw** [comment]
Confirmed now.
