### ISSUE TITLE
are the official guidelines outdated?

### ISSUE THREAD

**Issue by egonw** [jcheminform/jcheminform#24]
The [JCheminform. website](https://jcheminf.biomedcentral.com/submission-guidelines/preparing-your-manuscript/correspondence) states the following declarations: 

![image](https://user-images.githubusercontent.com/26721/201531856-f10caad5-d12a-4297-85c7-ae61ac75b6d1.png)

I just received an email with the following:

![image](https://user-images.githubusercontent.com/26721/201531889-41e6bd26-3d4b-4ddb-869a-5f378e2c6bd9.png)

Does the website's author guidelines need to be updated accordingly?

**Comment by mjsmyllie** [comment]
Ethical approval and consent to participate should not be required for JCheminf, thus the website should be correct. Please could you forward me the email?

**Comment by egonw** [comment]
Sent.

**Comment by mjsmyllie** [comment]
It was requested in error. Closing this ticket now.
