### ISSUE TITLE
FigShare font issues for some files uploaded to FigShare

### ISSUE THREAD

**Issue by ChemConnector** [jcheminform/jcheminform#4]
I was looking at supplementary files on FigShare at https://springernature.figshare.com/CHIN and there are font issues for some of the files that can be seen. For example: 
https://springernature.figshare.com/articles/MOESM3_of_MS-Ready_structures_for_non-targeted_high-resolution_mass_spectrometry_screening_studies/7033895

It appears to mostly be quotation marks

**Comment by egonw** [comment]
Follow up from FigShare: https://twitter.com/figshare/status/1107205585546723328

**Comment by egonw** [comment]
Still exists: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0369-0

![image](https://user-images.githubusercontent.com/26721/61181319-0c303f00-a625-11e9-830b-1598e7c8f731.png)

**Comment by mjsmyllie** [comment]
reported

**Comment by stuchalk** [comment]
Looks to me like its a Unicode issue, but why specifically the 't' in the suppinfo file is the only one is really strange...

**Comment by egonw** [comment]
Still applies. @ChemConnector, shall we close this? I do not think that after more than 1.5 yrs this will still get fixed.

**Comment by ChemConnector** [comment]
I would assume it is NOT going to get resolved at this point so move to
Done or Delete
Tony Williams

Phone: +1 (919) 201-1516
Email: tony27587@gmail.com
Skype: tony27587
My Blog: www.chemconnector.com
Twitter: http://twitter.com/ChemConnector
